#server port number
server:
  port: 7777

#mysql config properties
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/amazon
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    
 #hibernate properties   
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    
#view resolver
  mvc:
    view:
      prefix: /views/
      suffix: .jsp
      
#activating profiles
  profiles:
    active:
    - dev
    
